[package]
name = "refexer"
version = "0.1.0"
edition = "2024"
default-run = "refexer"

[dependencies]
anyhow = "1.0.100"
cpal = "0.16.0"
eframe = "0.33.3"
rand = "0.9.2"

[[bin]]
name = "refexer-gui"
path = "src/bin/egui/gui.rs"
